name: Run Unit Tests

on:
  push:
    branches: ["*"]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    # 1) Ensure Python can load your src/vbase_utils package
    env:
      PYTHONPATH: "${{ github.workspace }}/src:${{ env.PYTHONPATH }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install your package so imports work
          pip install -e .
          # Then install all dev requirements (pytest, yfinance, etc.)
          pip install -r requirements_dev.txt

      - name: Run unit tests
        run: |
          # Now your vbase_utils code is importable
          python -m unittest discover -s tests
          # Or, if you prefer pytest:
          # pytest
