name: Run Unit Tests

on:
  push:
    branches: ["*"]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    # 1) Tell Python to look inside your src/ folder for vbase_utils
    env:
      PYTHONPATH: "${{ github.workspace }}/src:${{ env.PYTHONPATH }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 2) Install your package in editable mode so vbase_utils is available
          pip install -e .
          # 3) Then install everything else (pytest, yfinance, etc.)
          pip install -r requirements_dev.txt

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests
